require 'json'

# Get the ID of the host IPFS
ipfs_info = JSON.parse `ipfs id`
master_id = ipfs_info['ID']

addresses = ipfs_info['Addresses']
addr = addresses.select { |i| i =~ /33.33.33./ }.first

Vagrant.configure("2") do |config|
  config.vm.provision "file",  source: "ipfs.conf", destination: "/home/vagrant/ipfs.conf"
  config.vm.provision "shell", path:   'setup.sh', args: addr
  config.vm.provision "shell", path:   'mount-registry.sh', args: master_id
  config.vm.provider "virtualbox" do |v|
    v.memory = 384
    v.cpus = 1
  end

  config.vm.define "ipfs-node-0" do |node|
    node.vm.box = "ubuntu-14.10_ipfs"
    node.vm.hostname = "ipfs-node-0"
    node.vm.network(:private_network, { ip: "33.33.33.100" })
  end
end
